### ISSUE TITLE
Not an issue but a question.

### ISSUE THREAD

**Issue by natifygh** [SAT-R/sa2#125]
Is this by chance portable or nah?

**Comment by freshollie** [comment]
Certainly not yet. Firstly 25% of the sourcecode is still in armv6 asm (for the GBA). Secondly, even if it was decompiled the source code could be compiled for PC but the resulting program would be useless as it depends on GBA specific hardware. The decompilation process is still about 6 months off, with a port likely to also take years to perfect.

**Comment by natifygh** [comment]
Ah I see, thanks!
